// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI60oFwySKgr3snQ9TbtUStpjnDn_jHFg',
    appId: '1:649951087316:web:225e1a7e5aa79f5d304941',
    messagingSenderId: '649951087316',
    projectId: 'world-explorer-697d6',
    authDomain: 'world-explorer-697d6.firebaseapp.com',
    storageBucket: 'world-explorer-697d6.firebasestorage.app',
    measurementId: 'G-YZKMK8DJ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtoYLpZHedGKIZ10uBLstfetc5Zg0M-BI',
    appId: '1:649951087316:android:b4910179e51eb40d304941',
    messagingSenderId: '649951087316',
    projectId: 'world-explorer-697d6',
    storageBucket: 'world-explorer-697d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRa6FuVtXKtc5K8LcBnls-EmDntY45ywo',
    appId: '1:649951087316:ios:11aba7a4a6a6397e304941',
    messagingSenderId: '649951087316',
    projectId: 'world-explorer-697d6',
    storageBucket: 'world-explorer-697d6.firebasestorage.app',
    iosBundleId: 'com.example.worldExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRa6FuVtXKtc5K8LcBnls-EmDntY45ywo',
    appId: '1:649951087316:ios:11aba7a4a6a6397e304941',
    messagingSenderId: '649951087316',
    projectId: 'world-explorer-697d6',
    storageBucket: 'world-explorer-697d6.firebasestorage.app',
    iosBundleId: 'com.example.worldExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI60oFwySKgr3snQ9TbtUStpjnDn_jHFg',
    appId: '1:649951087316:web:38b2da69e3e5a11f304941',
    messagingSenderId: '649951087316',
    projectId: 'world-explorer-697d6',
    authDomain: 'world-explorer-697d6.firebaseapp.com',
    storageBucket: 'world-explorer-697d6.firebasestorage.app',
    measurementId: 'G-ZBWEJ0FT4F',
  );
}
